USE SYI;

CREATE TABLE ACESSO(
	ID INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    CPF INT(11) NOT NULL UNIQUE,
    NOME VARCHAR(40),
    EMAIL VARCHAR(40),
    NASCIMENTO DATE NOT NULL,
    SENHA VARCHAR(8) NOT NULL
);

SELECT * FROM ACESSO;